---
- name: "install dependencies."
  become: true
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes

- name: "install pm2"
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

- name: "npm install"
  become: true
  command: npm install
  args:
    chdir: /home/ubuntu/backend

- name: "npm build"
  become: true
  command: npm run build
  args:
    chdir: /home/ubuntu/backend
    
    
- name: Start PM2
  command: pm2 start npm --name backend -- start
  args:
    chdir: /home/ubuntu/backend 
    