# ---
# - name: "install dependencies."
#   become: true
#   apt:
#     name: ["nodejs", "npm"]
#     state: latest
#     update_cache: yes

# - name: "install pm2"
#   become: true
#   npm:
#     name: pm2
#     global: yes
#     production: yes
#     state: present

# - name: "copy files from CircleCI to server"
#   copy:
#     src: /root/project/backend/dist.zip
#     dest: /home/ubuntu

# - name: unzip dist.zp to have the backend folder
#   ansible.builtin.unarchive:
#     src: /home/ubuntu/dist.zip
#     dest: /home/ubuntu
#     remote_src: yes

# - name: "npm install"
#   become: true
#   command: npm install
#   args:
#     chdir: /home/ubuntu/backend

# - name: "npm build"
#   become: true
#   command: npm run build
#   args:
#     chdir: /home/ubuntu/backend

# - name: "install express"
#   become: true
#   command: npm install express --save-dev
#   args:
#     chdir: /home/ubuntu/backend
    
# - name: Start PM2
#   become: true
#   command: pm2 start npm --name backend -- start
#   args:
#     chdir: /home/ubuntu/backend

################################
# NEW CODE                     #                                            
################################

---
- name: Creates backend directory
  file:
    path: /home/ubuntu/backend
    state: directory

- name: Print the current directory
  shell: pwd

- name: Copy backend dist files web server
  copy:
    src: ~/project/artifact.tar.gz
    dest: /home/ubuntu/backend/artifact.tar.gz
    remote_src: yes

- name: Uncompress Backend
  shell: |
    cd /home/ubuntu/backend
    tar xvzf artifact.tar.gz -C .
    ls -la
    
- name: Build
  become: true
  shell: |
    cd /home/ubuntu/backend
    npm install
    npm run build
- name: "initialize pm2"
  become: yes
  shell: pm2 ls
  args:
    chdir: /home/ubuntu/backend

- name: "start pm2"
  become: yes
  shell: pm2 start --name "backend" npm -- start
  args:
    chdir: /home/ubuntu/backend