 
  
- name: "npm install"
  command: npm install
  args:
    chdir: /home/ubuntu/backend

- name: "Run Build"
  command: npm run build
  args:
    chdir: /home/ubuntu/backend

- name: "use pm2 to run the node server"
  command: pm2 start npm -- run "start:dev"
  args:
    chdir: /home/ubuntu/backend


    